### ISSUE TITLE
Link button not working

### ISSUE THREAD

**Issue by RuneDemomn** [KettleMC-Network/OptifineChecker#2]
Hello.
Great mod idea and we would like to possibly add this to our modpack, unfortunately the link button does not seem to be working. When we click "link" nothing happens.

**Comment by RuneDemomn** [comment]
[15:54:11] [Client thread/ERROR]: Couldn't open link!
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URI$Parser.parse(URI.java:3042)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URI.<init>(URI.java:588)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.net.URI.create(URI.java:850)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.kettlemc.opticheck.OptiCheckScreen.func_146284_a(OptiCheckScreen.java:50)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[15:54:11] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LeStegii** [comment]
Hey, what version of the mod are you using?

**Comment by LeStegii** [comment]
@RuneDemomn I tried both versions of the mod (1.7 and 1.12), both of them worked fine for me with default settings, what link did you enter?

**Comment by RuneDemomn** [comment]
Latest updates have resolved this.
